@startuml
'https://plantuml.com/class-diagram

class Category {
String name
getName()
setName()
toString()
}

class Validator {
isNotBlankAndNull()
}

class Introducer {
inputNameCategory()
}


@enduml